spring:
  application:
    name: bkn-booking
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bkn-booking
    username: postgres
    password: PGFamo2369

server:
  port: ${PORT:8082}
  servlet:
    context-path: /bkn-booking

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
